### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by kgnfth** [mave12/Mars_Stealer_v8#1]
in builder
Host = `host.com`
Gate = `gate.php`
Encryption pass some random string
after running the builded.exe and after some seconds it stops and self destructs the builded.exe
but no logs are getting

Also looking at the requests made from builded.exe,
it only makes a GET request to `host.com/gate.php` and `host.com/request`

did u test and does it work for you ?

**Comment by Doc-Strange1** [comment]
its most likely a clipper please do not run it

**Comment by kgnfth** [comment]
> its most likely a clipper please do not run it

its not

those request i am talking about are to my own host for the panel
